name: ustaad_flutter
description: Trusted local service bookings.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  image_picker: ^1.2.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/ustaad_logo.png
    - assets/branding/ustaad_logo_light.png
    - assets/branding/ustaad_icon.png
