name: ustaad_flutter
description: Trusted local service bookings.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.9
  flutter_animate: ^4.5.2
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  flutter_map: ^7.0.2
  http: ^1.5.0
  image_picker: ^1.2.2
  latlong2: ^0.9.1
  permission_handler: ^11.4.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.2
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/ustaad_logo.png
    - assets/branding/ustaad_logo_light.png
    - assets/branding/ustaad_icon.png
